# https://github.com/jamesmullenbach/caml-mimic/blob/master/predictions/CAML_mimic3_50/train_new_model.sh
# data
data_dir: data/MIMIC-50
data_name: MIMIC-50
min_vocab_freq: 3
max_seq_length: 2500
# We follow caml-mimic that includes labels in both training and test datasets.
include_test_labels: true

# train
seed: 1337
epochs: 50 # 200
batch_size: 2 # 16
optimizer: adamax
learning_rate: 0.0001 # 0.001
weight_decay: 0
patience: 10
shuffle: false

# eval
eval_batch_size: 1
monitor_metrics: ['Micro-F1', 'Macro-F1', 'Another-Macro-F1', 'P@1', 'P@3', 'P@5']
val_metric: P@5

# model
model_name: BERTAttention
init_weight: null
network_config:
  dropout: 0.2
  lm_weight: emilyalsentzer/Bio_ClinicalBERT
  lm_window: 512
  embedding_dim: 512
  num_heads: 2
