activation: tanh
batch_size: 16
config: example_config/MIMIC-50/caml.yml
cpu: false
data_dir: data/MIMIC-50
data_name: MIMIC-50
data_workers: 1
display_iter: 100
dropout: 0.2
embed_file: data/MIMIC-50/processed_full.embed
epochs: 200
eval: false
eval_batch_size: 1
filter_sizes: [10]
label_file: null
learning_rate: 0.0001
load_checkpoint: null
max_seq_length: 2500
metrics_thresholds: [0.5]
min_vocab_freq: 3
model_name: CAML
momentum: 0.9
monitor_metrics: ['P@1','P@3','P@5']
num_filter_per_size: 50
optimizer: adam
patience: 10
predict_out_path: null
result_dir: runs/optuna-50
seed: 1337
test_path: data/MIMIC-50/test.txt
train_path: data/MIMIC-50/train.txt
val_metric: P@5
val_path: null
val_size: 0.2
vocab_file: data/MIMIC-50/vocab.csv
vocab_label_map: null
weight_decay: 0
fixed_length: true
init_weight: null
