data_name: AmazonCat-13K
training_file: /l/users/dongli.he/libml/LibMultiLabel/AmazonCat-13K/train.txt
training_sparse_file: /l/users/dongli.he/libml/LibMultiLabel/AmazonCat-13K/train_ver3.svm
test_file: /l/users/dongli.he/libml/LibMultiLabel/AmazonCat-13K/test.txt
# pretrained embeddings
embed_file: glove.840B.300d
embed_cache_dir: /l/users/dongli.he/libml/LibMultiLabel/embedding
# save path
result_dir: /l/users/dongli.he/libml/LibMultiLabel/AmazonCat-13K/results

# preprocessing
min_vocab_freq: 1
max_seq_length: 500

# label tree related parameters
cluster_size: 8
save_k_predictions: 64

# data
batch_size: 200
val_size: 4000
shuffle: true

# eval
eval_batch_size: 200
monitor_metrics: [P@1, P@3, P@5, nDCG@3, nDCG@5, RP@3, RP@5]
val_metric: nDCG@5

# train
seed: 1337
epochs: 10
# https://github.com/Lightning-AI/lightning/issues/8826
optimizer: Adam
optimizer_config:
  lr: 0.001
# early stopping
patience: 5
silent: true

# model
model_name: AttentionXML
network_config:
  embed_dropout: 0.2
  post_encoder_dropout: 0.5
  rnn_dim: 1024
  rnn_layers: 1
  linear_size: [512, 256]
  freeze_embed_training: false
