# data
data_dir: data/EUR-Lex
data_name: EUR-Lex
min_vocab_freq: 1
max_seq_length: 500
include_test_labels: true

# train
seed: 1337
epochs: 50
batch_size: 16
optimizer: adam
learning_rate: 0.001
weight_decay: 0
patience: 10
shuffle: true

# eval
eval_batch_size: 64
monitor_metrics: ['Micro-F1', 'Macro-F1', 'Another-Macro-F1', 'P@1', 'P@3', 'P@5']
val_metric: P@1

# model
model_name: BiGRULWAN
init_weight: null
network_config:
  rnn_dim: 300
  rnn_layers: 1
  embed_dropout: 0.4
  encoder_dropout: 0

# pretrained vocab / embeddings
embed_file: glove.6B.200d